default_stage:
  default_modifiers:
    QuantizationModifier:
      ignore: [lm_head]
      config_groups:
        group_0:
          targets: [Linear]
          weights:
            num_bits: 8
            type: float
            strategy: channel
            dynamic: false
            observer: minmax
            symmetric: true
          input_activations:
            num_bits: 8
            type: float
            strategy: tensor
            dynamic: false
            observer: minmax
            symmetric: true